name: Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-latest, macos-15, windows-latest, windows-11-arm]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
        run: npm run electron-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        env:
          GH_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
        with:
          name: electron-build-${{ matrix.os }}
          path: dist/

  create-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        env:
          GH_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
        with:
            path: ./artifacts

      - name: Create GitHub Release

        uses: softprops/action-gh-release@v2

        with:
          files: ./artifacts/**

        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
